"use client";

import React from "react";
import { Card } from "@/components/ui/Card";
import { Zap, TrendingUp, Sparkles, Clock } from "lucide-react";

export function PredictionCard({ goal }: { goal?: any }) {
    const predictions = goal?.predictions ? (typeof goal.predictions === 'string' ? JSON.parse(goal.predictions) : goal.predictions) : null;
    const benchmarks = predictions?.benchmarks || {};
    const racePrediction = predictions?.racePrediction;

    return (
        <Card>
            <div className="flex items-center justify-between mb-6">
                <h3 className="text-xs font-black text-neutral-400 uppercase tracking-widest flex items-center gap-2">
                    <Zap size={14} className="text-amber-500" />
                    AI Performance Forecast
                </h3>
                <div className="px-2 py-0.5 bg-amber-50 rounded-full text-[8px] font-black text-amber-600 uppercase tracking-wider">
                    Powered by Gemini
                </div>
            </div>

            <div className="space-y-6">
                {racePrediction && (
                    <div className="bg-primary/5 p-4 rounded-2xl border border-primary/10 mb-4">
                        <p className="text-[10px] font-black text-primary uppercase tracking-widest mb-1">Target Race Prediction</p>
                        <div className="text-2xl font-black text-foreground">{racePrediction}</div>
                        <p className="text-[10px] text-neutral-500 font-medium mt-1">Based on course profile & current form.</p>
                    </div>
                )}

                <div className="grid grid-cols-1 gap-4">
                    <div className="flex items-center justify-between">
                        <div className="flex items-center gap-2">
                            <div className="w-1 h-4 bg-neutral-200 rounded-full" />
                            <span className="text-sm font-bold text-neutral-500">5K</span>
                        </div>
                        <span className="text-lg font-black text-foreground">{benchmarks['5k'] || "--:--"}</span>
                    </div>
                    <div className="flex items-center justify-between">
                        <div className="flex items-center gap-2">
                            <div className="w-1 h-4 bg-neutral-200 rounded-full" />
                            <span className="text-sm font-bold text-neutral-500">10K</span>
                        </div>
                        <span className="text-lg font-black text-foreground">{benchmarks['10k'] || "--:--"}</span>
                    </div>
                    <div className="flex items-center justify-between">
                        <div className="flex items-center gap-2">
                            <div className="w-1 h-4 bg-neutral-200 rounded-full" />
                            <span className="text-sm font-bold text-neutral-500">Half Marathon</span>
                        </div>
                        <span className="text-lg font-black text-foreground">{benchmarks['half'] || "--:--:--"}</span>
                    </div>
                </div>
            </div>

            <div className="mt-6 pt-6 border-t border-neutral-100 italic text-[10px] text-neutral-400 font-medium">
                Predictions are generated by analyzing your CTL/ATL trends and recent intensity distribution.
            </div>
        </Card>
    );
}
